Repository Automattic/fb-instant-articles, pull requests merged in 2022-09, with the labels that each got.

#1095 Add GitHub workflow to mark issues and PR as stale
  .github/workflows/stale.yml
Labels: type: maintenance

#1073 Update release.sh
  release.sh
Labels: [Status] Stale

#1076 Reduce plugin's cache burden, remote requests
  embeds.php
Labels: [Status] Stale

#831 Fix the way filters are applied in `get_cover_media`
  class-instant-articles-post.php
Labels: type: bug
